name: Install copilot CLI tool to Action Runner and run svc deploy

on:
  workflow_call:
    inputs:
      app:
        description: 'Copilot application to deploy within'
        required: true
        type: string
      env:
        description: 'Copilot environment to deploy within'
        required: true
        type: string
      name:
        description: 'Copilot service name to deploy'
        required: true
        type: string
      version:
        description: 'Copilot version to install'
        default: 'v1.32.0'
        required: false
        type: string


jobs:
  install-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Install copilot
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        # download copilot
        curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/${{ inputs.version }}/copilot-linux && \
        # make copilot bin executable
        chmod +x copilot-linux && \
        # move to path
        mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
        # add to PATH
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: svc deploy
      run: |
        copilot -help
        copilot svc deploy -a ${{ inputs.app }} -e ${{ inputs.env }} -n ${{ inputs.name }}