name: Use Copilot to deploy app to an environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub repo environment name'
        required: true
        type: string
      cp_app:
        description: 'copilot app name'
        required: true
        type: string
      cp_env:
        description: 'copilot env name'
        required: true
        type: string
      cp_svc:
        description: 'copilot svc name'
        required: true
        type: string
      aws_region:
        description: 'region for AWS_ROLE_TO_ASSUME'
        required: true
        type: string
      aws_registry:
        description: 'region for AWS_ROLE_TO_ASSUME'
        required: true
        type: string
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: 'IAM role with copilot permissions'
        required: true

jobs:
  svc-deploy:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.aws_registry }}
    - name: Copilot svc deploy
      uses: ksivamuthu/aws-copilot-github-action@v0.0.6
      with:
          command: deploy
          app: ${{ env.cp_app }}
          env: ${{ env.cp_env }}
          name: ${{ env.cp_svc }}
