name: Determine github environment based on branch

on:
  workflow_call:

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Select Environment
        id: select-environment
        run: |
          if [[ "${{ github.head_ref }}" ]]
          then
            echo "${{ github.head_ref }}"
            export VALUE="${{ github.head_ref }}"
          else
            echo "${{ github.ref }}"
            export VALUE="${{ github.ref }}"
          fi
          case $VALUE in
            main) echo "github-environment=prod" >> "$GITHUB_OUTPUT" ;
            beta) echo "github-environment=beta" >> "$GITHUB_OUTPUT" ;;
            test) echo "github-environment=test" >> "$GITHUB_OUTPUT" ;;
            *) echo "github-environment=dev" >> "$GITHUB_OUTPUT" ;;
          esac
          echo "$GITHUB_OUTPUT"
    outputs:
      github-environment: ${{ steps.select-environment.outputs.github-environment }}