name: Determine github environment based on branch

on:
  workflow_call:
    outputs:
      github-environment:
        description:
        value: ${{ jobs.determine-environment.outputs.github-environment }}

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      github-environment: ${{ steps.select-environment.outputs.github-environment }}
    steps:
      - id: select-environment
        run: |
          if [[ "${{ github.head_ref }}" ]]
          then
            echo "${{ github.head_ref }}"
            export VALUE="${{ github.head_ref }}"
          else
            echo "${{ github.ref }}"
            export VALUE="${{ github.ref }}"
          fi
          case $VALUE in
            main) echo "github-environment=prod" >> "$GITHUB_OUTPUT" ;;
            beta) echo "github-environment=beta" >> "$GITHUB_OUTPUT" ;;
            test) echo "github-environment=test" >> "$GITHUB_OUTPUT" ;;
            *) echo "github-environment=dev" >> "$GITHUB_OUTPUT" ;;
          esac
      - run: echo ${{ steps.select-environment.outputs.github-environment }}
  echo:
    runs-on: ubuntu-latest
    needs: determine-environment
    steps:
      - run: echo ${{ needs.determine-environment.select-environment.outputs.github-environment }}
