# build and push to ghcr.io, scan with trivy
name: Docker Image Build, Push and Scan

on:
  workflow_call:
    inputs:
      context:
        description: 'Docker build context path'
        default: '.'
        type: string
      file:
        description: 'Dockerfile path'
        default: './Dockerfile'
        type: string

env:
  git_commit: ${{ github.sha }}
  REPO: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: downcase REPO
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build
      id:   build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64
        context: "{{ defaultContext }}:${{ inputs.context }}"
        file: ${{ inputs.file }}
        load: true
        cache-to: |
          type=registry,mode=max,ref=ghcr.io/${{ env.REPO }}:latest
        cache-from: |
          type=registry,ref=ghcr.io/${{ env.REPO }}:latest
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          GIT_COMMIT=${{ env.git_commit }}
        tags: |
          ghcr.io/${{ env.REPO }}:${{ env.git_commit }}
          ghcr.io/${{ env.REPO }}:latest
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ env.REPO }}:${{ env.git_commit }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'
    - name: Docker push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        context: "{{ defaultContext }}:${{ inputs.context }}"
        file: ${{ inputs.file }}
        push: true
        tags: |
          ghcr.io/${{ env.REPO }}:${{ env.git_commit }}
          ghcr.io/${{ env.REPO }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
