# build and push to ghcr.io, scan with trivy
name: Docker Image Build, Push and Scan

on:
  workflow_call:
    inputs:
      context:
        description: 'Docker build context path'
        default: '.'
        type: string
      file:
        description: 'Dockerfile path'
        default: './Dockerfile'
        type: string

env:
  git_commit: ${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to ECR
      uses: docker/login-action@v2
      with:
          registry: ${{ vars.AWS_REGISTRY }}
    - name: Docker build
      id:   build
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        context: "{{ defaultContext }}:${{ inputs.context }}"
        file: ${{ inputs.file }}
        load: true
        build-args: |
          GIT_COMMIT=${{ env.git_commit }}
        tags: |
          ${{ vars.AWS_REGISTRY }}/${{ github.repository }}:${{ env.git_commit }}
          ${{ vars.AWS_REGISTRY }}/${{ github.repository }}:latest
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ vars.AWS_REGISTRY }}/${{ github.repository }}:${{ env.git_commit }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'
    - name: Docker push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        context: ${{ steps.build.outputs.context }}
        file: ${{ inputs.file }}
        push: true
        tags: ${{ steps.build.outputs.tags }}
