# build and push to ghcr.io, scan with trivy
name: Docker Image Build, Push and Scan

on:
  workflow_call:
    inputs:
      gcr_tag:
        description: 'Tag of image saved in GitHub Container Registry (head SHA from PR)'
        required: true
        type: string
      context:
        description: 'Docker build context path'
        default: '.'
        type: string
      file:
        description: 'Dockerfile path'
        default: './Dockerfile'
        type: string
      name:
        description: ''
        default: ''
        type: string
        required: true

env:
  REPO: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: downcase REPO
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build
      id:   build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64
        context: "{{ defaultContext }}:${{ inputs.context }}"
        # use original file name when building image
        file: ${{ inputs.file }}
        load: true
        cache-to: type=gha,mode=max
        cache-from: type=gha
        build-args: |
          GIT_COMMIT=${{ inputs.gcr_tag }}
        # use input name when tagging and pushing for registries
        tags: |
          ghcr.io/${{ env.REPO }}/${{ inputs.name }}:latest
          ghcr.io/${{ env.REPO }}/${{ inputs.name }}:${{ inputs.gcr_tag }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ env.REPO }}/${{ inputs.name }}:${{ inputs.gcr_tag }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'
    - name: Docker push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64
        context: "{{ defaultContext }}:${{ inputs.context }}"
        file: ${{ inputs.file }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          GIT_COMMIT=${{ inputs.gcr_tag }}
        tags: |
          ghcr.io/${{ env.REPO }}/${{ inputs.name }}:${{ inputs.gcr_tag }}
          ghcr.io/${{ env.REPO }}/${{ inputs.name }}:latest
