name: Republish Docker Image from ghcr to ecr

on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub environment name'
        required: true
        type: string
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: 'IAM role with ecr permissions'
        required: true

env:
  git_commit: ${{ github.sha }}
  REPO:       ${{ github.repository }}
jobs:
  republish:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write   # This is required for requesting the OIDC JWT
      packages: read   # This is required for ghcr.io pull
    runs-on: ubuntu-latest
    steps:
    - name: downcase REPO
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull prior job built image
      run: docker pull ghcr.io/${{ env.REPO }}:${{ env.git_commit }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Login to ECR
      uses: docker/login-action@v2
      with:
          registry: ${{ vars.AWS_REGISTRY }}
    - name: Docker tag
      run: |
        docker tag ghcr.io/${{ env.REPO }}:${{ env.git_commit }} ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}:${{ env.git_commit }}
        docker tag ghcr.io/${{ env.REPO }}:${{ env.git_commit }} ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}:${{ inputs.environment }}
    - name: Docker push
      run: docker push -a ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}
