name: Republish Docker Image from ghcr to ecr

on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub environment name'
        required: true
        type: string
      gcr_tag:
        description: 'Tag of image saved in GitHub Container Registry (head SHA from PR)'
        required: true
        type: string
      file:
        description: 'Dockerfile path for built image to be republished.'
        default: ''
        required: false
        type: string
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: 'IAM role with ecr permissions'
        required: true

env:
  REPO: ${{ github.repository }}
  FILE: ${{ inputs.file }}

jobs:
  republish:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write   # This is required for requesting the OIDC JWT
      packages: read   # This is required for ghcr.io pull
    runs-on: ubuntu-latest
    steps:
    - name: downcase REPO
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
    - name: downcase File name
      if: ${{ inputs.file }} != ''
      run: FILE_VAR=${{ env.FILE }} && echo "FILE=${FILE_VAR,,}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull prior job base built image from GHCR
      run: docker pull ghcr.io/${{ env.REPO }}:${{ inputs.gcr_tag }}
    - name: Pull prior job named built image from GHCR
      if: ${{ inputs.file }} != ''
      run: docker pull ghcr.io/${{ env.REPO }}/${{ env.FILE }}:${{ inputs.gcr_tag }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Login to ECR
      uses: docker/login-action@v2
      with:
          registry: ${{ vars.AWS_REGISTRY }}

    ## If a specific file name is passed in, find the built (lowercase) image in ghcr to republish to ECR
    - name: Docker tag named image from GHCR
      if: ${{ inputs.file }} != ''
      run: |
        docker tag ghcr.io/${{ env.REPO }}/${{ env.FILE }}:${{ inputs.gcr_tag }} ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}/${{ env.FILE }}:${{ github.sha }}
        docker tag ghcr.io/${{ env.REPO }}/${{ env.FILE }}:${{ inputs.gcr_tag }} ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}/${{ env.FILE }}:${{ inputs.environment }}
    - name: Docker push named image to ECR
      if: ${{ inputs.file }} != ''
      run: docker push -a ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}/${{ env.FILE }}

    ## Else, use the base repo name to find the image
    - name: Docker tag base image from GHCR
      if: ${{ inputs.file }} == ''
      run: |
        docker tag ghcr.io/${{ env.REPO }}:${{ inputs.gcr_tag }} ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
        docker tag ghcr.io/${{ env.REPO }}:${{ inputs.gcr_tag }} ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}:${{ inputs.environment }}
    - name: Docker push base image to ECR
      if: ${{ inputs.file }} == ''
      run: docker push -a ${{ vars.AWS_REGISTRY }}/${{ env.REPO }}
