name: Generic CI workflow that runs GCD image with an override for the specific notebook to run

on:
  workflow_call:
    inputs:
      notebook:
        description: 'Notebook to run inside GCD image'
        required: true
        type: string
      image-tag:
        description: 'Tag of GCD image to use, defaults to latest'
        type: string
        default: latest
      schema:
        description: 'Snowflake schema param to be passed into notebook, default <repo>_<PR#>'
        type: string
        default: ${{ github.event.repository.name }}_${{ github.event.number }}
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: 'IAM role with ECR permissions'
        required: true

jobs:
  notebook-CI:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2
    - name: Checkout latest (or specified version) of gcd image from ECR    
      env:
        ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Set env
      run: echo "PR_DERIVED_SCHEMA_NAME=$(echo ${{ inputs.schema }})" >> $GITHUB_ENV
    # TODO use jq to rename kernel to python3 and remove 'instance_type'
    - name: Setup notebook kernel config
      run: |
        echo "$(jq '.metadata.kernelspec.name = "python3" | del(.metadata.instance_type)' notebooks/papermill.ipynb)" > notebooks/papermill.ipynb
    # Create snowflake schema! Notebook expects it to exist
    - name: Create snowflake schema
      uses: anecdotes-ai/snowflake-query@v1.2
      with:
        snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        snowflake_username: ${{ secrets.SNOWFLAKE_USER }}
        snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
        queries: |
          CREATE OR REPLACE SCHEMA ${{ vars.SNOWFLAKE_DATABASE }}.${{ github.event.repository.name }}_${{ github.event.number }}
    - name: Run that above image with the specified notebook as entrypoint override
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ inputs.image-tag }}
        # Mount repo into container's home directory
        options: -v ${{ github.workspace }}:/home/jovyan
        run: |
          jupyter nbconvert --to notebook --execute ${{ inputs.notebook }}
    # TODO artifact mounted output/** (except 'archive') for this PR