name: Generic CD workflow that preps a PR build for release by renaming the PR's Snowflake schema to the merge commit hash

on:
  workflow_call:
    inputs:
      notebook:
        description: 'Notebook to run inside GCD image'
        required: true
        type: string
      schema:
        description: 'Snowflake schema param to be renamed, default <repo>_<PR#>'
        type: string
        default: ${{ github.event.repository.name }}_${{ github.event.number }}
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: 'IAM role with ECR permissions'
        required: true

jobs:
  notebook-CD:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Run Snowflake query
      uses: anecdotes-ai/snowflake-query@v1.2
      with:
        snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        snowflake_username: ${{ secrets.SNOWFLAKE_USER }}
        snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
        queries: 'call system$wait(5);
                  select CURRENT_VERSION()
                  '
                  # TODO do alter schema here
                  # From  ${{ github.event.repository.name }}_${{ github.event.number }} 
                  # To    ${{ github.event.repository.name }}_${{ github.event.pull_request.head.sha }}
