name: Pytest

on:
  workflow_call:
    inputs:
      cmd:
        description: 'Command to run before pip install'
        required: false
        default: ''
        type: string
      python_version:
        description: 'Python version for installation and testing'
        required: true
        type: string
      pytest_args:
        description: 'Additional arguments for pytest. Ex. pytest <dir/tests>'
        required: false
        default: ''
        type: string

jobs:
  pytest:
    name: "Launch tests with pytest"
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python ${{ inputs.python_version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Run command
        if: ${{ inputs.cmd != '' }}
        run: ${{ inputs.cmd }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Run Pytest
        run: |
          source venv/bin/activate
          pytest ${{ inputs.pytest_args }}
