name: Validate that secrets in service manifest exist in a copilot environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub repo environment name'
        required: true
        type: string
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: 'IAM role with copilot permissions'
        required: true

jobs:
  secret-check:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Get secrets from manifest.yml
      id: manifestSecrets
      uses: mikefarah/yq@master
      with:
        cmd: yq -oj '.secrets | keys' copilot/${{ vars.COPILOT_SERVICE }}/manifest.yml
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Get secrets from Param Store in SSM
      id: ssmSecrets
      run: |
        echo "ssmSecrets=$(aws ssm get-parameters-by-path --output json --recursive --path /copilot/${{ vars.COPILOT_APPLICATION }}/${{ vars.COPILOT_ENVIRONMENT }}/secrets | jq '.Parameters[].Name' | jq -s -c)" >> $GITHUB_OUTPUT  
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Compare Secrets Python
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          ssmSecrets = ${{ steps.ssmSecrets.outputs.ssmSecrets }}
          manifestSecrets = ${{ steps.manifestSecrets.outputs.result }}
          manifestSet = set(manifestSecrets)
          ssmSet = set()

          # strip prefix from ssmSecrets and the Sets should be identical
          for s in ssmSecrets:
            ssmSet.add(s.split("/")[-1])

          if manifestSet - ssmSet != set():
            print("ERROR: Following secrets exist in manifest but not in SSM. Check the Param Store")
            print(manifestSet - ssmSet)
            exit(1)
          if ssmSet - manifestSet != set():
            print("ERROR: Following secrets exist in SSM but not in the manifest. Check the service manifest.yml")
            print(ssmSet - manifestSet)
            exit(1)
          exit(0)